---
title: "Grabaciones de las Clases"
toc: true

---

## Clase 5: dplyr 📊

En esta clase se explica el uso de `dplyr` en R para la manipulación y transformación de datos. Se trabajan funciones fundamentales como `select()`, `filter()`, `mutate()`, `arrange()` y `summarise()`, herramientas esenciales para el análisis de datos de manera clara y eficiente. 🚀

{{< video https://youtu.be/sO6cEIuCrMU >}}


## Clase 6 RMarkdown

En este video te explico qué es RMarkdown, cómo funciona y cómo puedes usarlo para crear reportes reproducibles combinando código, texto, tablas y gráficos en un solo documento.

📌 Vas a aprender:

- Qué es RMarkdown
- Cómo crear un archivo .Rmd
- Estructura básica de un documento
- Bloques de código (chunks)
- Cómo generar HTML, PDF y Word
- Integración con R y visualizaciones

## Archivos creados en la clase 

- [ theme cerulean](https://dra-lindaaimara.github.io/Archivos_Rmarkdown/Rmardown_dplyr_theme_cerulean.Rmd)
- [ theme prettydoc](https://dra-lindaaimara.github.io/Archivos_Rmarkdown/Rmardown_theme_prettydoc.Rmd)

{{< video https://www.youtube.com/watch?v=6vDMQlzO1tM >}}


## Clase 8 RProject 


Aprende qué es un RProject y cómo usar la librería RStudio junto con here para organizar tus proyectos de manera profesional 📊💻

En este video explicamos qué es un RProject, por qué es importante trabajar con proyectos en RStudio y cómo la librería here ayuda a manejar rutas de archivos de forma sencilla y sin errores. 🚀

📌 En esta clase aprenderás:

- Qué es un RProject
- Ventajas de trabajar con proyectos en RStudio
- Cómo crear un nuevo proyecto
- Organización de carpetas y archivos
- Uso de la librería here
- Cómo evitar errores de rutas


{{< video https://youtu.be/yZyALiyXuwU >}}

## Clase 9 prueba de hipótesis

En esta clase se presenta una introducción práctica a la prueba de hipótesis utilizando el lenguaje de programación R 💻. A lo largo del video se revisan y aplican algunas de las pruebas estadísticas más utilizadas en el análisis de datos, como el t-test y el z-test 📐, las cuales permiten evaluar afirmaciones sobre parámetros poblacionales a partir de información muestral.

Además, se emplea la librería ggpubr 📈 para facilitar la visualización y presentación de los resultados, integrando el análisis estadístico con gráficos claros y bien estructurados. El objetivo de esta sesión es que el estudiante comprenda tanto el fundamento teórico 🧠 como la implementación práctica en R 🛠️ de las pruebas de hipótesis, fortaleciendo sus habilidades de análisis e interpretación de datos

{{< video https://www.youtube.com/watch?v=_afjDsjTTug >}}

## Clase 10 Introducción a Google Colab 
🚀 Introducción a Google Colab | Primeros pasos en Python para análisis de datos

En esta clase aprenderás a usar Google Colab desde cero y darás tus primeros pasos en Python aplicado al análisis de datos 📊🐍

Durante la práctica vimos:

✅ Cómo usar notebooks en Google Colab
✅ Variables y operaciones básicas en Python
✅ Listas y ciclos for
✅ Introducción a pandas
✅ Creación de DataFrames
✅ Visualización de datos con gráficas
✅ Comparación entre R y Python


{{< video https://www.youtube.com/watch?v=DWVUEBW4fac >}}


